<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="9" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
      <class name="javateam2.LRUMapTest">
        <test-method status="PASS" signature="testConstructorType1()" name="testConstructorType1" duration-ms="0" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
        </test-method>
        <test-method status="PASS" signature="testConstructorSize()" name="testConstructorSize" duration-ms="0" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
        </test-method>
        <test-method status="PASS" signature="testConstructorException()" name="testConstructorException" duration-ms="0" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
        </test-method>
        <test-method status="PASS" signature="testConstructorType2()" name="testConstructorType2" duration-ms="0" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
        </test-method>
        <test-method status="FAIL" signature="testSize()" name="testSize" duration-ms="0" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[-1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.remove(ArrayList.java:390)
	at javateam2.LRUMap.get(LRUMap.java:32)
	at javateam2.LRUMapTest.testSize(LRUMapTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:676)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1169)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1182)
	at org.testng.TestRunner.privateRun(TestRunner.java:761)
	at org.testng.TestRunner.run(TestRunner.java:612)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:241)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1169)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1094)
	at org.testng.TestNG.run(TestNG.java:1006)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:107)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:199)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:170)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testPut()" name="testPut" duration-ms="0" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
        </test-method>
        <test-method status="PASS" signature="testSize3()" name="testSize3" duration-ms="0" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
        </test-method>
        <test-method status="PASS" signature="testGetNull2()" name="testGetNull2" duration-ms="0" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
        </test-method>
        <test-method status="FAIL" signature="testGetNull()" name="testGetNull" duration-ms="0" started-at="2011-11-18T09:29:01Z" finished-at="2011-11-18T09:29:01Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[-1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.remove(ArrayList.java:390)
	at javateam2.LRUMap.get(LRUMap.java:32)
	at javateam2.LRUMapTest.testGetNull(LRUMapTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:676)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1169)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1182)
	at org.testng.TestRunner.privateRun(TestRunner.java:761)
	at org.testng.TestRunner.run(TestRunner.java:612)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:241)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1169)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1094)
	at org.testng.TestNG.run(TestNG.java:1006)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:107)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:199)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:170)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
